default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres

development:
  <<: *default
  database: edu_rails_development

test:
  <<: *default
  database: edu_rails_test

staging:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
